//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zoo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        public string AnimalID { get; set; }
        public string AnimalName { get; set; }
        public System.DateTime Animalbirth { get; set; }
        public string KindID { get; set; }
        public string CageID { get; set; }
    
        public virtual Cage Cage { get; set; }
        public virtual Kind Kind { get; set; }
    }
}
